### PR TITLE
fix: Stop echoing everything in bdd tests' ci.sh files

### LINKED ISSUE #976: We shouldn't be echoing secrets in build/test/release
Let's cut down on our echoing, specifically to try to prevent echoing out secrets.

### PR DESCRIPTION
**Pull request by abayer**
fixes #976

Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>

### CODE REVIEW

File: bdd/bbs/ci.sh [hunk 1]
```diff
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 set -e
-set -x
```
Comment (hferentschik) [inline bdd/bbs/ci.sh:3]: +1, less is more

File: bdd/tekton/ci.sh [hunk 2]
```diff
@@ -90,7 +89,7 @@ kubectl config set-context --current --namespace=lh-test
 curl https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.14.2/release.yaml | sed -E "s/namespace\: tekton-pipelines/namespace: lh-test/" > install-tekton.yml
 kubectl apply -f install-tekton.yml
 
-# HMAC token is just a random 42 byte hex string we'll be using in Lighthosue and the webhook
+# HMAC token is just a random 42 byte hex string we'll be using in Lighthouse and the webhook
```
Comment (hferentschik) [inline bdd/tekton/ci.sh:92]: :-)

File: charts/lighthouse/Makefile [hunk 3]
```diff
@@ -35,7 +35,7 @@ release: clean
 	helm lint
 	helm init --client-only
 	helm package .
-	curl --fail -u $(CHARTMUSEUM_USER):$(CHARTMUSEUM_PASS) --data-binary "@$(NAME)-$(shell sed -n 's/^version: //p' Chart.yaml).tgz" $(CHART_REPO)/api/charts
+	@curl --fail -u $(CHARTMUSEUM_USER):$(CHARTMUSEUM_PASS) --data-binary "@$(NAME)-$(shell sed -n 's/^version: //p' Chart.yaml).tgz" $(CHART_REPO)/api/charts
```
Comment (hferentschik) [inline charts/lighthouse/Makefile:38]: +1, I think we can thin out the rules in these `Makefiles` altogether, but I can create a PR for that.

**Review by hferentschik — APPROVED** [review]

**Comment by hferentschik** [comment]
/lgtm

Nice one. Context is good, but unnecessary noise annoying.
