### PR TITLE
fix: Fix codegen by moving repoconfig out of apis

### LINKED ISSUE #926: Code gen is broken
The commit https://github.com/jenkins-x/lighthouse/commit/8353df545b1987eb04fd6e24130c3cd8ff30ee5f#diff-f26c1f2e029e419697a22d9c956a92aa moved some files in `pkg/apis/lighthouse/v1alpha1`.

Unfortunately those types are breaking code gen.

### PR DESCRIPTION
**Pull request by abayer**
Switches us away from using jx's codegen stuff to a more "pure" `hack/update-codegen.sh` approach.

Also adds a call to `make generate-client` to the `pr-build` context.

fixes #926

Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>

### CODE REVIEW

**Comment by abayer** [comment]
So I'm gonna ditch the reuse of jx's codegen and switch to something more like Tekton's.

**Comment by eddycharly** [comment]
I can LGTM without being in the reviewers list ?

**Comment by hferentschik** [comment]
> Switches us away from using jx's codegen stuff to a more "pure" hack/update-codegen.sh approach.

+100

File: Makefile [hunk 1]
```diff
@@ -149,9 +149,9 @@ $(CODEGEN_BIN):
 
 generate-client: codegen-clientset fmt ## Generate the client
 
-codegen-clientset: $(CODEGEN_BIN) ## Generate the k8s types and clients
+codegen-clientset: ## Generate the k8s types and clients
```
Comment (hferentschik) [inline Makefile:152]: I guess the actual _CODE_GEN_ rule can be removed in this case as well:

```
CODEGEN_BIN := $(GOPATH)/bin/codegen
$(CODEGEN_BIN):
	$(GO_NOMOD) get github.com/jenkins-x/jx/cmd/codegen
```

+1 for getting rid of the jx codegen.

File: Makefile [hunk 2]
```diff
@@ -149,9 +149,9 @@ $(CODEGEN_BIN):
...
 	@echo "Generating Kubernetes Clients for pkg/apis/lighthouse/v1alpha1 in pkg/client for lighthouse.jenkins.io:v1alpha1"
-	$(CODEGEN_BIN) --generator-version $(CLIENTSET_GENERATOR_VERSION) clientset --output-package=pkg/client --input-package=pkg/apis --group-with-version=lighthouse:v1alpha1
+	./hack/update-codegen.sh
```
Comment (hferentschik) [inline Makefile:154]: 👍

File: bdd/capture-failed-pod-logs.sh [hunk 3]
```diff
@@ -3,7 +3,6 @@ set -e
 set -x
 
 mkdir -p extra-logs
-kubectl logs --tail=-1 "$(kubectl get pod -l app=controllerbuild -o jsonpath='{.items[*].metadata.name}')" > extra-logs/controllerbuild.log
```
Comment (hferentschik) [inline bdd/capture-failed-pod-logs.sh:6]: no idea what this is about, but I am sure you know ;-)

File: go.mod [hunk 4]
```diff
@@ -28,13 +28,16 @@ require (
 	k8s.io/api v0.17.6
 	k8s.io/apimachinery v0.17.6
 	k8s.io/client-go v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible
+	k8s.io/code-generator v0.18.0
```
Comment (hferentschik) [inline go.mod:31]: go figure. Any idea why go modules decides on v0.18.0?

File: hack/generate-groups.sh [hunk 5]
```diff
@@ -0,0 +1,92 @@
+#!/usr/bin/env bash
+
+# Copyright 2017 The Kubernetes Authors.
```
Comment (hferentschik) [inline hack/generate-groups.sh:3]: what's the take on the license headers? In particular the copyright statement? The codebase is really all over the place. Personally I am not a fan of adding the license header for each file. AFAIU the Apache License just requires the LICENSE to be added once. 

I am in particular wondering about the copyright statement.

File: hack/update-codegen.sh [hunk 6]
```diff
@@ -0,0 +1,44 @@
+#!/usr/bin/env bash
+
+# Copyright 2019 The Tekton Authors
```
Comment (hferentschik) [inline hack/update-codegen.sh:3]: here we have "Tekton Authors" !?

File: pkg/repoconfig/merge/combine.go [hunk 7]
```diff
@@ -1,12 +1,12 @@
 package merge
 
 import (
-	"github.com/jenkins-x/lighthouse/pkg/apis/lighthouse/v1alpha1"
 	"github.com/jenkins-x/lighthouse/pkg/config"
+	"github.com/jenkins-x/lighthouse/pkg/repoconfig"
```
Comment (hferentschik) [inline pkg/repoconfig/merge/combine.go:5]: so we go from generated types to fixed ones? Are we fixing a regression here or what is actually happening here? So `RepositoryConfig` never meant to be in the api package?

**Review by hferentschik — CHANGES_REQUESTED** [review]

**Comment by hferentschik** [comment]
@abayer FYI - https://github.com/abayer/lighthouse/pull/1. I removed the unused make rule and did some other bits in pieces in `Makefile`.

File: Makefile (hunk 1 above)
Comment (abayer) [reply Makefile:152]: Yup, removing now.

File: go.mod (hunk 4 above)
Comment (abayer) [reply go.mod:31]: I never have a clue. =)

File: hack/generate-groups.sh (hunk 5 above)
Comment (abayer) [reply hack/generate-groups.sh:3]: Copy-pasted from Tekton's (same reason for the `update-codegen.sh` one), and I tend to not remove copyright headers. I'll remove the license, though, since it's unnecessary.

File: pkg/repoconfig/merge/combine.go (hunk 7 above)
Comment (abayer) [reply pkg/repoconfig/merge/combine.go:5]: Yeah, it shouldn't have ever been in the api package. That was a screw-up on my part asking for that. Pretty much everything around `repoconfig` is unfinished/in need of revisiting, so I just thought it'd be best to get it out of `pkg/apis` for now.

File: hack/generate-groups.sh (hunk 5 above)
Comment (hferentschik) [reply hack/generate-groups.sh:3]: ok.

File: pkg/repoconfig/merge/combine.go (hunk 7 above)
Comment (hferentschik) [reply pkg/repoconfig/merge/combine.go:5]: > Yeah, it shouldn't have ever been in the api package. That was a screw-up on my part asking for that. Pretty much everything around repoconfig is unfinished/in need of revisiting, so I just thought it'd be best to get it out of pkg/apis for now.

Ok, got you. Thanks for the clarification.

**Review by hferentschik — APPROVED** [review]
