### PR TITLE
fix: Check org members, not just collabs, for approve rights

### LINKED ISSUE #675: OWNERS not being read properly for some users
I'm really not sure what's causing this yet, but Gareth and I can approve things in a number of repos but no one else can. I think this is a concurrency issue but am not sure yet.

### PR DESCRIPTION
**Pull request by abayer**
fixes #675

Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>

### CODE REVIEW

File: pkg/webhook/webhook.go [hunk 1]
```diff
@@ -120,10 +119,18 @@ func (o *Options) Run() error {
...
 	}
 
-	o.localGitDir, err = ioutil.TempDir("", "git")
+	gitClient, err := git.NewClient(o.gitServerURL, o.gitKind())
 	if err != nil {
-		return errors.Wrapf(err, "failed to create git temp directory")
+		logrus.WithError(err).Fatal("Error getting git client.")
 	}
+	defer func() {
+		err := gitClient.Clean()
```
Comment (hferentschik) [inline pkg/webhook/webhook.go:127]: I guess I am a bit surprised to see a `Clean` here. What does a git client have to clean up?
Also, this is a controller, right and we are in the `Run` method, so this defer will execute when the whole controller dies. So is this just a cleanup to do things "right" or does this really try to fix anything and if so what?

Comment (hferentschik) [reply pkg/webhook/webhook.go:127]: Lighthouse is really too much of a black box for me atm. I will get a checkout and start poking around a bit. Then I will be able to give better feedback.

File: pkg/scmprovider/client.go [hunk 2]
```diff
@@ -47,6 +47,7 @@ type SCMClient interface {
 	// Functions implemented in organizations.go
 	ListTeams(string) ([]*scm.Team, error)
 	ListTeamMembers(int, string) ([]*scm.TeamMember, error)
+	ListOrgMembers(string) ([]*scm.TeamMember, error)
```
Comment (hferentschik) [inline pkg/scmprovider/client.go:50]: Not related, but the one function which sticks our is `DeleteStateComments`. Where is this coming from? I would have loved to see `StaleComments` and `DeleteComments`. But that's besides the point for this PR.

File: pkg/webhook/webhook.go (hunk 1 above)
Comment (abayer) [reply pkg/webhook/webhook.go:127]: So fwiw, the "git client" here needs to clean up because it mainly just does clones of repos to check their `OWNERS` files, so in theory when the process dies it should nuke the temp dir. The problem that this change is fixing is that we were doing that wayyyyyyy too much, in fact. So yeah, here, now that I've made it more like Prow behavior (just initing the git client once, not initing it each time we process a webhook), the cleanup should just be "doing things right".

File: pkg/scmprovider/client.go (hunk 2 above)
Comment (abayer) [reply pkg/scmprovider/client.go:50]: https://github.com/jenkins-x/lighthouse/blob/master/pkg/scmprovider/issues.go#L126 fwiw
